.TH "mate-panel-test-applets" "1" 
.SH "NAME" 
mate-panel-test-applets \(em  display installed applets 
.SH "SYNOPSIS" 
.PP 
\fBmate-panel-test-applets\fR [\fB\-\-help \fP]  
.SH "DESCRIPTION" 
.PP 
\fBmate-panel-test-applets\fR display installed applets in a 
dialog box and allow you to test them. 
.SH "OPTIONS" 
.IP "\fB\-\-help\fP" 10 
Display help 
.SH "AUTHOR" 
.PP 
This manual page was written by Christian Marillat marillat@debian.org for 
the \fBDebian GNU/Linux\fP system (but may be used by others). 
.\" created by instant / docbook-to-man, Sun 03 Dec 2006, 23:24 
