.TH "mate-desktop-item-edit" "1" 
.SH "NAME" 
mate-desktop-item-edit \(em  tool to edit .desktop file 
.SH "SYNOPSIS" 
.PP 
\fBmate-desktop-item-edit\fR [\fB\-\-create-new \fP]  [\fB\-\-help \fP]  
.SH "DESCRIPTION" 
.PP 
\fBmate-desktop-item-edit\fR allows you to edit .desktop file. 
.SH "OPTIONS" 
.IP "\fB\-\-create-new\fP" 10 
Create new file in the given directory. 
.IP "\fB\-\-help\fP" 10 
Display help 
.SH "AUTHOR" 
.PP 
This manual page was written by Christian Marillat marillat@debian.org for 
the \fBDebian GNU/Linux\fP system (but may be used by others). 
.\" created by instant / docbook-to-man, Sun 03 Dec 2006, 23:24 
