.\"
.\" mate-about manual page.
.\" (C) 2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH MATE-PANEL 1 "MATE"
.SH NAME
mate-panel \- Display the MATE panel
.SH SYNOPSIS
.B mate-about [\-\-replace]
.SH DESCRIPTION
The \fImate-panel\fP program provides the panels of the the MATE
desktop.
.PP
The panels are the areas on the desktop that contain, among other items,
the applications menu, application launchers, the notification area and
the window list.
.PP
Small applications called \fBapplets\fP can also be embedded in the
panels. The applets usually provide quick access to specific
features.
.SH OPTIONS
.TP
.I --replace
Replace an already running panel.
.SH BUGS
If you find bugs in the \fImate-panel\fP program, please report
these on https://bugzilla.gnome.org.
