##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-panel
    - autoconf-archive
    - clang
    - gcc
    - git
    - gobject-introspection
    - itstool
    - libcanberra
    - libmateweather
    - libsm
    - libwnck3
    - make
    - mate-common
    - mate-desktop
    - mate-menus
    - meson
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-panel
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libice-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmateweather-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - make
    - mate-common
    - meson
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-panel.git
    - autoconf-archive
    - clang-analyzer
    - clang
    - desktop-file-utils
    - gcc
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - libSM-devel
    - libcanberra-devel
    - libmateweather-devel
    - librsvg2-devel
    - libwnck3-devel
    - make
    - mate-common
    - mate-desktop-devel
    - mate-menus-devel
    - meson
    - redhat-rpm-config
    - yelp-tools

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libice-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmateweather-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - make
    - mate-common
    - meson
    - yelp-tools

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - '[ -f mate-common-1.24.1.tar.xz ] || curl -Ls -o mate-common-1.24.1.tar.xz https://github.com/mate-desktop/mate-common/releases/download/v1.24.1/mate-common-1.24.1.tar.xz'
  - tar xf mate-common-1.24.1.tar.xz
  - cd mate-common-1.24.1
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

  - cd ${START_DIR}
  - if [ ! -d gtk-layer-shell-build ]; then
  -     git clone --depth 1  https://github.com/wmww/gtk-layer-shell.git gtk-layer-shell-build
  - fi
  - cd gtk-layer-shell-build
  - meson _build --prefix /usr
  - ninja -C _build
  - ninja -C _build install

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude -i'mate-menus-build' -i'gtk-layer-shell-build' .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-panel-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
