##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-panel
    - autoconf-archive
    - clang
    - gcc
    - git
    - gobject-introspection
    - gtk-layer-shell
    - itstool
    - libcanberra
    - libmateweather
    - libsm
    - libwnck3
    - make
    - mallard-ducktype
    - mate-common
    - mate-desktop
    - mate-menus
    - meson
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-panel
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - ducktype
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk-layer-shell-dev
    - libice-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmateweather-dev
    - libpango1.0-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxrandr-dev
    - lsb-release
    - make
    - mate-common
    - meson
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-panel.git
    - autoconf-archive
    - clang-analyzer
    - clang
    - cppcheck-htmlreport
    - desktop-file-utils
    - gcc
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - gtk-layer-shell-devel
    - libSM-devel
    - libmateweather-devel
    - libwnck3-devel
    - make
    - mate-common
    - mate-desktop-devel
    - mate-menus-devel
    - meson
    - python3-mallard-ducktype
    - redhat-rpm-config
    - yelp-tools

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - ducktype
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk-layer-shell-dev
    - libice-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmateweather-dev
    - libpango1.0-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxrandr-dev
    - lsb-release
    - make
    - mate-common
    - meson
    - yelp-tools

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude -i'gtk-layer-shell-build' .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude -i'gtk-layer-shell-build' .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://raw.githubusercontent.com/${OWNER_NAME}/${REPO_NAME}/master/icons/16x16/${REPO_NAME}.png
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-panel-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
