/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2019 Christopher Billington
 * Copyright © 2020 Ilia Bozhinov
 * Copyright © 2022 Victoria Brekenfeld
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface ext_workspace_group_handle_v1_interface;
extern const struct wl_interface ext_workspace_handle_v1_interface;
extern const struct wl_interface wl_output_interface;

static const struct wl_interface *ext_workspace_v1_types[] = {
	NULL,
	&ext_workspace_group_handle_v1_interface,
	&ext_workspace_handle_v1_interface,
	&wl_output_interface,
	&wl_output_interface,
	&ext_workspace_handle_v1_interface,
	&ext_workspace_handle_v1_interface,
	&ext_workspace_group_handle_v1_interface,
};

static const struct wl_message ext_workspace_manager_v1_requests[] = {
	{ "commit", "", ext_workspace_v1_types + 0 },
	{ "stop", "", ext_workspace_v1_types + 0 },
};

static const struct wl_message ext_workspace_manager_v1_events[] = {
	{ "workspace_group", "n", ext_workspace_v1_types + 1 },
	{ "workspace", "n", ext_workspace_v1_types + 2 },
	{ "done", "", ext_workspace_v1_types + 0 },
	{ "finished", "", ext_workspace_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface ext_workspace_manager_v1_interface = {
	"ext_workspace_manager_v1", 1,
	2, ext_workspace_manager_v1_requests,
	4, ext_workspace_manager_v1_events,
};

static const struct wl_message ext_workspace_group_handle_v1_requests[] = {
	{ "create_workspace", "s", ext_workspace_v1_types + 0 },
	{ "destroy", "", ext_workspace_v1_types + 0 },
};

static const struct wl_message ext_workspace_group_handle_v1_events[] = {
	{ "capabilities", "u", ext_workspace_v1_types + 0 },
	{ "output_enter", "o", ext_workspace_v1_types + 3 },
	{ "output_leave", "o", ext_workspace_v1_types + 4 },
	{ "workspace_enter", "o", ext_workspace_v1_types + 5 },
	{ "workspace_leave", "o", ext_workspace_v1_types + 6 },
	{ "removed", "", ext_workspace_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface ext_workspace_group_handle_v1_interface = {
	"ext_workspace_group_handle_v1", 1,
	2, ext_workspace_group_handle_v1_requests,
	6, ext_workspace_group_handle_v1_events,
};

static const struct wl_message ext_workspace_handle_v1_requests[] = {
	{ "destroy", "", ext_workspace_v1_types + 0 },
	{ "activate", "", ext_workspace_v1_types + 0 },
	{ "deactivate", "", ext_workspace_v1_types + 0 },
	{ "assign", "o", ext_workspace_v1_types + 7 },
	{ "remove", "", ext_workspace_v1_types + 0 },
};

static const struct wl_message ext_workspace_handle_v1_events[] = {
	{ "id", "s", ext_workspace_v1_types + 0 },
	{ "name", "s", ext_workspace_v1_types + 0 },
	{ "coordinates", "a", ext_workspace_v1_types + 0 },
	{ "state", "u", ext_workspace_v1_types + 0 },
	{ "capabilities", "u", ext_workspace_v1_types + 0 },
	{ "removed", "", ext_workspace_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface ext_workspace_handle_v1_interface = {
	"ext_workspace_handle_v1", 1,
	5, ext_workspace_handle_v1_requests,
	6, ext_workspace_handle_v1_events,
};

