#!/bin/bash

set -e

pkgname=mate-panel

MATECONF_CONFIG_SOURCE=`usr/bin/mateconftool-2 --get-default-source`

/usr/bin/mateconftool-2 --config-source="${MATECONF_CONFIG_SOURCE}" --direct --unload \
	/etc/mateconf/schemas/panel-default-setup.entries > /dev/null

if [ -f /usr/sbin/mateconfpkg ]; then
	/usr/sbin/mateconfpkg --uninstall ${pkgname}
fi

exit 0
