libstatus_notifier = static_library('status-notifier',
  'sn-dbus-menu.c',
  'sn-dbus-menu.h',
  'sn-dbus-menu-item.c',
  'sn-dbus-menu-item.h',
  'sn-flat-button.c',
  'sn-flat-button.h',
  'sn-host-v0.c',
  'sn-host-v0.h',
  'sn-item.c',
  'sn-item.h',
  'sn-item-v0.c',
  'sn-item-v0.h',
  gnome.gdbus_codegen('sn-dbus-menu-gen',
    'com.canonical.dbusmenu.xml',
    namespace: 'Sn',
  ),
  gnome.gdbus_codegen('sn-host-v0-gen',
    'org.kde.StatusNotifierHost.xml',
    namespace: 'Sn',
  ),
  gnome.gdbus_codegen('sn-item-v0-gen',
    'org.kde.StatusNotifierItem.xml',
    namespace: 'Sn',
  ),
  gnome.gdbus_codegen('sn-watcher-v0-gen',
    'org.kde.StatusNotifierWatcher.xml',
    namespace: 'Sn',
  ),
  include_directories: [include_directories('.'), include_directories('..')],
  dependencies: notification_area_deps + [m_dep],
  c_args: [
    '-DMATELOCALEDIR="@0@"'.format(mate_panel_localedir),
    '-DG_LOG_DOMAIN="notification-area-applet"',
  ] + disable_deprecated_flags,
)
